Set time2date and date2time to use Python Chandra.Time
sot/Ska-Convert pull request #2
Opened 2018-11-27 04:39 UTC by jeanconn

Set time2date and date2time to use Python Chandra.Time

There are really no useful tests include in the module.  I figured I'd just document the use cases in comments in this PR.

2018-11-27 05:04 UTC, jeanconn commented on Convert.pm
> +$VERSION = '4.2';
No idea what makes sense for a version for this.

2018-11-27 05:06 UTC, jeanconn commented
I think if starcheck will be the only user of Ska::Convert in ska3 that these changes are acceptable with these tests (which have consistent outputs with what is expected from Python Chandra.Time).  If we want to promote other applications on ska3, these changes will probably need further review and updated application tests.

2018-11-27 05:08 UTC, jeanconn commented
If we have confidence in Python Chandra.Time, I think it makes sense to make this change in Ska::Convert at the module level (so all the calls to from starcheck will hit the Python version and not need any additional Inline::Python patching in starcheck).  Re-running starcheck regression tests against this.

2018-11-27 12:01 UTC, taldcroft requested changes

2018-11-27 12:01 UTC, taldcroft commented on Convert.pm
> +    if ($date =~ /^\d{3}:\d{2}\:\d{2}:\d{2}\.\d{3}$/){
This regex is more restrictive than the original and doesn't allow for `"000:01:30:01.00"` or `"0:01:30:01.000"` that was fine in the original.  For least unexpected breakage I think you should try to keep the original logic even if it might fail in weird ways for bad inputs.  This is legacy code and so anything that calls it should be known to provide input that worked with the original.

So that means testing for a relative time by splitting and looking for year==0.

2018-11-27 12:01 UTC, taldcroft commented on Convert.pm
> +$VERSION = '4.2';
That's fine.

2018-11-27 12:03 UTC, jeanconn commented on Convert.pm
> +    if ($date =~ /^\d{3}:\d{2}\:\d{2}:\d{2}\.\d{3}$/){
Sure.  I don't think it matters for our current use case (only from starcheck) but I'll just put back the previous logic in its entirety for these.

2018-11-27 12:04 UTC, jeanconn commented on Convert.pm
> +    if ($date =~ /^\d{3}:\d{2}\:\d{2}:\d{2}\.\d{3}$/){
And I was not planning to install the updated Ska::Convert in ska2, so not sure how much we should consider it legacy-compatible.

2018-11-27 12:12 UTC, jeanconn commented on Convert.pm
> +    if (not $yr){
I think this is now equivalent to the previous 'unless ($yr)' though I don't know if we would be better off counting the pieces that you get if you split on the colons.

2018-11-27 12:21 UTC, jeanconn commented on Convert.pm
> +    if ($date =~ /^\d{3}:\d{2}\:\d{2}:\d{2}\.\d{3}$/){
Also, you suggest looking for "year == 0" but I thought it was just empty and I don't remember Perl/if they are equivalent.  Will check.

2018-11-27 14:58 UTC, jeanconn commented
Also note, that if we're using Inline::Python, I think we have to defined PYTHONHOME .  We could probably do this in flt_envs at some point (I don't know if it would conflict with anything).  Right now this happens in the starcheck wrappers for testing and flight.

2018-11-27 16:22 UTC, jeanconn commented
I also couldn't get this to install as a perl module in conda with the Inline::Python dependence, so I just pushed it into the tarball installed set of Perl modules.  Will need more rigorous integration testing (right now I've just copied it into my dev ska for starcheck testing.  I'll rebuild a ska3 dev ska around the conda packages and retest).

2019-02-01 19:40 UTC, taldcroft commented
Was there a reason not to call Chandra::Time and stay in the perl universe?

2019-02-01 19:46 UTC, jeanconn commented
I think the primary driver for me was that Chandra.Time was right and Chandra::Time was sometimes right?  And I was in a hurry for starcheck support so this happened all in 

https://github.com/sot/skare3-static/commit/2163dc6d767f41953a9e9a5265b1e72c2d74a262

So we can go a bunch of different ways on this.  Easiest might be for me to remove Ska::Convert from starcheck calls altogether and then revert Ska::Convert to a Perl-only package.

2019-02-01 19:52 UTC, jeanconn commented
Probably somewhat related to https://github.com/sot/Ska-Convert/pull/1#issuecomment-273892264

2019-02-01 19:56 UTC, taldcroft commented
Ska::Convert is used in a few places:
```
kadi$ find . -name '*.pl' | xargs grep 'Ska::Convert'
./starcheck/starcheck/src/starcheck.pl:use Ska::Convert qw( date2time );
./timelines/parse_cmd_load_gen.pl:use Ska::Convert qw( date2time );
./arc/arc.pl:use Ska::Convert qw(time2date date2time);
./arc/arc.pl:# - Fix Ska::Convert to make time2date having configurable format
./arc/arc_time_machine.pl:use Ska::Convert qw( time2date );
./arc/get_iFOT_events.pl:use Ska::Convert qw(:all);
./arc/get_web_content.pl:use Ska::Convert qw(time2date date2time);
./arc/parse_cm_file.pl:use Ska::Convert qw(date2time time2date);
./aca_movie/aca_movie.pl:use Ska::Convert qw(time2date date2time);
./aca_bgd_mon/aca_bgd_mon.pl:use Ska::Convert qw(date2time time2date);
./aca_bgd_mon/aca_img_hist.pl:use Ska::Convert qw(time2date);
./aca_bgd_mon/extr_products.pl:use Ska::Convert qw(time2date);
./aca_bgd_mon/get_products.pl:use Ska::Convert qw(time2date);
./astromon/get_cat_obs_data.pl:use Ska::Convert qw(time2date radec_dist);
./astromon/get_cat_obs_data.pl:use Ska::Convert qw(dec2hms radec_dist hms2dec);
./astromon/get_cat_obs_data.pl:use Ska::Convert qw(dec2hms);
./dark_cal_att_gen/attitude.pl:use Ska::Convert;
./dark_cal_att_gen/attitude.pl:# use Ska::Convert::date2time to get CXC time in seconds
./dark_cal_att_gen/attitude.pl:    my $time_seconds = Ska::Convert::date2time($datestring);
./Ska-AGASC/compare.pl:use Ska::Convert qw(date2time);
./Ska-Convert/test.pl:use Ska::Convert qw(:all);
```
 I don't see any open issues on Chandra-Time so not sure about the "sometimes right".  It seems like the main likely issue is related to leap seconds.

From what I can see this was never merged, so not clear what you mean about "reverting" it.  I'm liking #1 now.  :smile:

2019-02-01 20:01 UTC, jeanconn commented
Indeed.  I don't know if whatever issue I had resolved itself.  The bigger issue with Chandra::Time vs Chandra.Time is that both need to be rebuilt for new leap seconds, which doubles maintenance but whatever.

With regard to "reverting" it, this integrated Python code is live in ska3/flight because the code went in  as part of ska-classic in the skare3-static link I referenced above.

2019-03-19 20:10 UTC, jeanconn commented
Using #1 instead.

2019-03-19 20:10 UTC, closed without merging